apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
      annotations:
        instrumentation.opentelemetry.io/inject-python: "default/splunk-otel-collector"
    spec:
      containers:
      - name: flask-container
        image: rmanjunatha/my-flask-app:v1
        ports:
        - containerPort: 5001
        env:
        - name: "SPLUNK_PROFILER_ENABLED"
          value: "true"
        - name: "DD_DYNAMIC_INSTRUMENTATION_ENABLED"
          value: "true"
        - name: "DD_SYMBOL_DATABASE_UPLOAD_ENABLED"
          value: "true"
